# Generated by Django 5.2.13 on 2026-04-25 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bars", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BacktestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timeframe", models.CharField(default="1d", max_length=8)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "initial_capital",
                    models.DecimalField(decimal_places=2, default=10000, max_digits=18),
                ),
                (
                    "commission_bps",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Commission in basis points (1 bps = 0.01%).",
                    ),
                ),
                ("slippage_bps", models.PositiveIntegerField(default=0)),
                ("params", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backtest_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "symbols",
                    models.ManyToManyField(related_name="runs", to="bars.symbol"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RunMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("return_pct", models.FloatField(blank=True, null=True)),
                ("buy_hold_return_pct", models.FloatField(blank=True, null=True)),
                ("annualized_return_pct", models.FloatField(blank=True, null=True)),
                ("cagr_pct", models.FloatField(blank=True, null=True)),
                ("volatility_pct", models.FloatField(blank=True, null=True)),
                ("sharpe_ratio", models.FloatField(blank=True, null=True)),
                ("sortino_ratio", models.FloatField(blank=True, null=True)),
                ("calmar_ratio", models.FloatField(blank=True, null=True)),
                ("alpha_pct", models.FloatField(blank=True, null=True)),
                ("beta", models.FloatField(blank=True, null=True)),
                ("max_drawdown_pct", models.FloatField(blank=True, null=True)),
                ("avg_drawdown_pct", models.FloatField(blank=True, null=True)),
                (
                    "max_drawdown_duration_days",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "avg_drawdown_duration_days",
                    models.FloatField(blank=True, null=True),
                ),
                ("trade_count", models.IntegerField(default=0)),
                ("win_rate_pct", models.FloatField(blank=True, null=True)),
                ("best_trade_pct", models.FloatField(blank=True, null=True)),
                ("worst_trade_pct", models.FloatField(blank=True, null=True)),
                ("avg_trade_pct", models.FloatField(blank=True, null=True)),
                ("profit_factor", models.FloatField(blank=True, null=True)),
                ("expectancy_pct", models.FloatField(blank=True, null=True)),
                ("sqn", models.FloatField(blank=True, null=True)),
                ("kelly_criterion", models.FloatField(blank=True, null=True)),
                (
                    "final_equity",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "peak_equity",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "commissions_paid",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("exposure_time_pct", models.FloatField(blank=True, null=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="runs.backtestrun",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "run metrics",
            },
        ),
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "code",
                    models.TextField(
                        help_text="Python source defining the Strategy class."
                    ),
                ),
                (
                    "entrypoint",
                    models.CharField(
                        default="Strategy",
                        help_text="Class name to load from the code body.",
                        max_length=120,
                    ),
                ),
                ("params_schema", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="strategies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "strategies",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="backtestrun",
            name="strategy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="runs.strategy",
            ),
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("long", "Long"), ("short", "Short")],
                        default="long",
                        max_length=8,
                    ),
                ),
                ("qty", models.DecimalField(decimal_places=8, max_digits=24)),
                ("entry_ts", models.DateTimeField()),
                ("entry_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("exit_ts", models.DateTimeField(blank=True, null=True)),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "pnl",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("return_pct", models.FloatField(blank=True, null=True)),
                (
                    "commission_paid",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("duration_seconds", models.BigIntegerField(blank=True, null=True)),
                ("tag", models.CharField(blank=True, max_length=120)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="runs.backtestrun",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="bars.symbol",
                    ),
                ),
            ],
            options={
                "ordering": ["run", "entry_ts"],
            },
        ),
        migrations.CreateModel(
            name="EquityPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.DateTimeField()),
                ("equity", models.DecimalField(decimal_places=8, max_digits=20)),
                ("drawdown_pct", models.FloatField(blank=True, null=True)),
                ("drawdown_duration_days", models.FloatField(blank=True, null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equity_points",
                        to="runs.backtestrun",
                    ),
                ),
            ],
            options={
                "ordering": ["run", "ts"],
                "indexes": [
                    models.Index(
                        fields=["run", "ts"], name="runs_equity_run_id_4aee24_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="backtestrun",
            index=models.Index(
                fields=["status", "-created_at"], name="runs_backte_status_8ef1f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="backtestrun",
            index=models.Index(
                fields=["strategy", "-created_at"],
                name="runs_backte_strateg_4d30c8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["run", "entry_ts"], name="runs_trade_run_id_209d3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["symbol", "-entry_ts"], name="runs_trade_symbol__15c32b_idx"
            ),
        ),
    ]
