# Generated by Django 5.2.13 on 2026-04-25 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bars", "0002_timescaledb_hypertable"),
        ("runs", "0002_timescaledb_hypertable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParameterSweep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timeframe", models.CharField(default="1d", max_length=8)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "initial_capital",
                    models.DecimalField(decimal_places=2, default=10000, max_digits=18),
                ),
                ("commission_bps", models.PositiveIntegerField(default=20)),
                ("slippage_bps", models.PositiveIntegerField(default=0)),
                ("base_params", models.JSONField(blank=True, default=dict)),
                (
                    "grid",
                    models.JSONField(
                        default=dict,
                        help_text='{"param_name": [v1, v2, v3]} or {"param_name": {"start":5,"stop":30,"step":5}}',
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("children_total", models.PositiveIntegerField(default=0)),
                ("children_succeeded", models.PositiveIntegerField(default=0)),
                ("children_failed", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parameter_sweeps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sweeps",
                        to="runs.strategy",
                    ),
                ),
                (
                    "symbols",
                    models.ManyToManyField(related_name="sweeps", to="bars.symbol"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="backtestrun",
            name="sweep",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="runs",
                to="runs.parametersweep",
            ),
        ),
        migrations.AddIndex(
            model_name="parametersweep",
            index=models.Index(
                fields=["status", "-created_at"], name="runs_parame_status_261238_idx"
            ),
        ),
    ]
