# Generated by Django 5.2.13 on 2026-04-25 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ticker", models.CharField(db_index=True, max_length=32, unique=True)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("exchange", models.CharField(blank=True, max_length=32)),
                (
                    "asset_class",
                    models.CharField(
                        choices=[
                            ("equity", "Equity"),
                            ("etf", "ETF"),
                            ("crypto", "Crypto"),
                            ("fx", "Forex"),
                            ("future", "Future"),
                            ("index", "Index"),
                        ],
                        default="equity",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["ticker"],
            },
        ),
        migrations.CreateModel(
            name="Bar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ts", models.DateTimeField(db_index=True)),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("1d", "1 Day"),
                            ("1h", "1 Hour"),
                            ("15m", "15 Minutes"),
                            ("5m", "5 Minutes"),
                            ("1m", "1 Minute"),
                        ],
                        default="1d",
                        max_length=8,
                    ),
                ),
                ("open", models.DecimalField(decimal_places=8, max_digits=20)),
                ("high", models.DecimalField(decimal_places=8, max_digits=20)),
                ("low", models.DecimalField(decimal_places=8, max_digits=20)),
                ("close", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "volume",
                    models.DecimalField(decimal_places=8, default=0, max_digits=24),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bars",
                        to="bars.symbol",
                    ),
                ),
            ],
            options={
                "ordering": ["symbol", "-ts"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "-ts"], name="bars_bar_symbol__8a6817_idx"
                    ),
                    models.Index(
                        fields=["timeframe", "-ts"], name="bars_bar_timefra_b1c7ef_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("symbol", "ts", "timeframe"),
                        name="uq_bar_per_symbol_ts_tf",
                    )
                ],
            },
        ),
    ]
